Add mention that subject could get claims from server side sessions.
DuendeSoftware/docs.duendesoftware.com pull request #507
Opened 2024-08-12 17:45 UTC by RolandGuijt

2024-08-13 14:09 UTC, josephdecock requested changes
I think we should incorporate this into the previous paragraph to make which claims you'll get more obvious. If server side sessions are on, we always use that. If they're off, then we give you different claims depending on the context.

2024-08-13 14:19 UTC, josephdecock commented
And maybe we can explain the the claims identity at the time of grant creation is stored in the grant store. So if you are in the profile service in the context of using a grant (exchanging a code for a token, etc), we can give you those claims, but if you are in the user info endpoint, we don't have anything except what is in the access token sent to the user info endpoint.

2024-08-14 09:52 UTC, RolandGuijt commented
@josephdecock I've used bullets now to create an if..then structure which should be more clear.

2024-08-14 14:53 UTC, josephdecock commented on IdentityServer/v7/docs/content/reference/services/profile_service.md
> +        - If the _ProfileService_ is called in the context of a grant (e.g. exchanging a code for a token) the claims stored in the grant store will be used.
This is good, but I think it raises another question - which claims are stored in the grant store?

Maybe something like this:

```suggestion
        - If the _ProfileService_ is called in the context of a grant (e.g. exchanging a code for a token), the claims associated with that grant in the grant store will be used. When grants are stored, by default a snapshot of the logged in user's claims are captured with the grant.
```

2024-08-14 15:02 UTC, RolandGuijt commented
Agreed.

2024-08-14 16:19 UTC, merged